[package]

name = "icmpmessaging"
version = "0.0.1"
authors = ["unknown"]
build = "build.rs"

[dependencies]
rand = "*"
libc = "*"
time = "*"
log = "*"
getopts = "*"
term = "*"
rustc-serialize = "*"

[dependencies.ncurses]
git = "https://github.com/jeaye/ncurses-rs.git"

