[package]

name = "stealthy"
version = "0.0.1"
authors = ["unknown"]
build = "build.rs"

[dependencies]
rand = "*"
libc = "*"
time = "*"
getopts = "*"
term = "*"

[dependencies.ncurses]
git = "https://github.com/jeaye/ncurses-rs.git"

[features]
default = ["usencurses"]
usencurses = []
